#
# config.yml for TrickOrTreat
#

common:
  locale: "de-DE"

request:
  timeout: 5
  cooldown: 10

treat:
  lovecount: 10
  lovedelay: 10

trick:
  port:
  - "world:170:67:269:0:0"
  - "world:158:67:269:0:0"
  - "world:164:78:252:0:0"

ghost:
  cleanInterval: 400
  maxLived: 12000
  dropCount: 15
  dropDelay: 15
  spawncooldown: 5000
  spawnCount: 3
  spawn:
  - "world:164:73:260:0:0"
