#
# config.yml for TrickOrTreat
#

common:
  languagefile: "en.yml"
  worldname: "world"

request:
  requestTimeout: 5
  requestCooldown: 10

trick:

treat:

ghost:
  cleanInterval: 400
  maxLived: 12000
  dropCount: 5
  dropDelay: 15
