#
# config.yml for TrickOrTreat
#

common:
  languagefile: "en.yml"
  worldname: "world"

request:
  requestTimeout: 5
  requestCooldown: 10

trick:

treat:
  port:
  - "-235:69:196:0:0"
  - "-209:68:190:0:0"
  - "-230:69:218:0:0"

ghost:
  cleanInterval: 400
  maxLived: 12000
  dropCount: 15
  dropDelay: 15
  spawn: "-225:75:200:0:0"
  spawncooldown: 5000
