name: TrickOrTreat
version: 2.0
author: scottec
description:
depend: [WorldGuard, CsApi]
main: net.scottec.TrickOrTreat.TrickOrTreat

commands:
  tot:
    description:
    usage: /tot <subcommand...>
    aliases:
    permission: trickortreat.config
    permission-message: No permission

  tottoggle:
    description:
    usage: /tottoggle
    aliases:
